#!/usr/bin/with-contenv bash

mkdir -p /config/{templates,coredns}

echo "Uname info: $(uname -a)"
# check for wireguard module
ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
    echo "**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****"
    ip link del dev test
    if capsh --current | grep "Current:" | grep -q "cap_sys_module"; then
        echo "**** As the wireguard module is already active you can remove the SYS_MODULE capability from your container run/compose. ****"
    fi
else
    echo "**** The wireguard module is not active. If you believe that your kernel should have wireguard support already, make sure that it is activated via modprobe! ****"
    echo "****  If you have an old kernel without wireguard support built-in, you can try using the "legacy" tag for this image to compile the modules from scratch.   ****"
    sleep infinity
fi
