#!/usr/bin/with-contenv bash

mkdir -p /config/{templates,coredns}

echo "Uname info: $(uname -a)"
# check for wireguard module
ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
    echo "**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****"
    ip link del dev test
else
    echo "**** The wireguard module is not active. If you believe that your kernel should have wireguard support already, make sure that it is activated via modprobe! ****"
    sleep infinity
fi
