#!/usr/bin/with-contenv bash

rm -rf /etc/wireguard
mkdir -p /etc/wireguard

if [[ -z ${PUBLIC_KEY} || -z ${END_POINT} ]]; then
  echo "[$(date -Iseconds)] Finding the best server..."
  recommendations=$(curl -s "https://api.nordvpn.com/v1/servers/recommendations?&filters\[servers_technologies\]\[identifier\]=wireguard_udp&limit=1&${QUERY}")
  server=$(jq -r '.[0] | del(.services, .technologies)' <<< "${recommendations}")
  if [[ -z ${server} ]]; then
    echo "[$(date -Iseconds)] Unable to select a server ¯\_(⊙︿⊙)_/¯"
    sleep infinity
  fi
  echo "[$(date -Iseconds)] Using server: ${server}"
  if [[ -z ${PUBLIC_KEY} ]]; then
    PUBLIC_KEY=$(jq -r '.[0].technologies[] | select( .identifier == "wireguard_udp" ) | .metadata[] | select( .name == "public_key" ) | .value' <<< "${recommendations}")
  fi
  if [[ -z ${END_POINT} ]]; then
    END_POINT=$(jq -r '.[0].hostname' <<< "${recommendations}"):51820
  fi
fi

cat >/etc/wireguard/wg0.conf <<EOL
[Interface]
PrivateKey = ${PRIVATE_KEY}
ListenPort = ${LISTEN_PORT:-51820}
Address = ${ADDRESS:-10.5.0.2/32}
DNS = ${DNS:-103.86.96.100,103.86.99.100}
Table = ${TABLE:-auto}
PreUp = ${PRE_UP}
PostUp = ${POST_UP}
PreDown = ${PRE_DOWN}
PostDown = ${POST_DOWN}

[Peer]
PublicKey = ${PUBLIC_KEY}
AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0}
Endpoint = ${END_POINT}
PersistentKeepalive = ${PERSISTENT_KEEP_ALIVE:-25}
EOL

chmod 600 /etc/wireguard/wg0.conf

echo "[$(date -Iseconds)] Connecting..."
wg-quick up wg0 
echo "[$(date -Iseconds)] Connected! \(ᵔᵕᵔ)/"

if [[ -n ${RECONNECT} ]]; then
  echo "[$(date -Iseconds)] Reconnecting in ${RECONNECT} seconds"
  sleep "${RECONNECT}"
  wg show wg0 | grep transfer
  echo "[$(date -Iseconds)] Reconnecting..."
  exit 0
fi

sleep infinity & PID=$!
trap "kill $PID; exit" INT TERM
wait
