#!/usr/bin/with-contenv bash

rm -rf /etc/wireguard
mkdir -p /etc/wireguard

if [[ -z ${PUBLIC_KEY} || -z ${END_POINT} ]]; then
  echo "Finding the best server..."
  recommendations=$(curl -s "https://api.nordvpn.com/v1/servers/recommendations?&filters\[servers_technologies\]\[identifier\]=wireguard_udp&limit=1&${QUERY}")
  if [[ -z ${PUBLIC_KEY} ]]; then
    PUBLIC_KEY=$(jq -r '.[0].technologies[] | select( .identifier == "wireguard_udp" ) | .metadata[] | select( .name == "public_key" ) | .value' <<< "${recommendations}")
  fi
  if [[ -z ${END_POINT} ]]; then
    END_POINT=$(jq -r '.[0].hostname' <<< "${recommendations}"):51820
  fi
fi

if [[ -n ${RECONNECT} ]]; then
  RECONNECT="s6-sleep ${RECONNECT} s6-svc -r /run/s6/services/wireguard &"
fi

cat >/etc/wireguard/wg0.conf <<EOL
[Interface]
PrivateKey = ${PRIVATE_KEY}
ListenPort = ${LISTEN_PORT:-51820}
Address = ${ADDRESS:-10.5.0.2/32}
DNS = ${DNS:-103.86.96.100,103.86.99.100}
Table = ${TABLE:-auto}
PreUp = ${PRE_UP}
PostUp = ${POST_UP}
PreDown = ${PRE_DOWN}
PostDown = ${POST_DOWN}
PostUp = ${RECONNECT}

[Peer]
PublicKey = ${PUBLIC_KEY}
AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0}
Endpoint = ${END_POINT}
PersistentKeepalive = ${PERSISTENT_KEEP_ALIVE:-25}
EOL

chmod 600 /etc/wireguard/wg0.conf

echo "Connecting..."
wg-quick up wg0 
wg show wg0

sleep infinity & PID=$!
trap "kill $PID; exit" INT TERM
wait
