#!/usr/bin/with-contenv bash

if [[ -z ${PUBLIC_KEY} || -z ${END_POINT} ]]; then
  echo "[$(date -Iseconds)] Finding the best server..."
  api_url="https://api.nordvpn.com/v1/servers/recommendations?filters"
  technology_filter="\[servers_technologies\]\[identifier\]=wireguard_udp"
  
  # Get the country code from the country name (if provided) and add it to the API URL as a filter
  if [[ -n ${COUNTRY_CODE} ]]; then
    country_id=$(curl --silent "https://api.nordvpn.com/v1/servers/countries" | jq --raw-output ".[] | select(.code == \"${COUNTRY_CODE}\") | [.name, .id] | \"\(.[1])\"")
    echo "[$(date -Iseconds)] Country ID: ${country_id}"
    country_filter="\[country_id\]=${country_id}"
    api_url="${api_url}${country_filter}&${technology_filter}"
    echo "[$(date -Iseconds)] API URL: ${api_url}"
  else
    api_url="${api_url}${technology_filter}"
  fi

  recommendations=$(curl --retry 3 -LsS "${api_url}&${QUERY}&limit=1")
  server=$(jq -r '.[0] | del(.services, .technologies)' <<< "${recommendations}")
  echo "[$(date -Iseconds)] Server: ${server}"
  if [[ -z ${server} ]]; then
    echo "[$(date -Iseconds)] Unable to select a server ¯\_(⊙︿⊙)_/¯"
    sleep infinity
  fi
#   echo "[$(date -Iseconds)] Using server: ${server}"
  if [[ -z ${PUBLIC_KEY} ]]; then
    PUBLIC_KEY=$(jq -r '.[0].technologies[] | select( .identifier == "wireguard_udp" ) | .metadata[] | select( .name == "public_key" ) | .value' <<< "${recommendations}")
  fi
  if [[ -z ${END_POINT} ]]; then
    END_POINT=$(jq -r '.[0].hostname' <<< "${recommendations}"):51820
  fi
fi

[[ -z "${PRIVATE_KEY}" ]] && [[ -f "${PRIVATE_KEY_FILE}" ]] && PRIVATE_KEY="$(head -n 1 "${PRIVATE_KEY_FILE}")"

( umask 077 && { cat >/etc/wireguard/wg0.conf <<-EOF
[Interface]
PrivateKey = ${PRIVATE_KEY}
ListenPort = ${LISTEN_PORT:-51820}
Address = ${ADDRESS:-10.5.0.2/32}
DNS = ${DNS:-103.86.96.100,103.86.99.100}
Table = ${TABLE}
PreUp = ${PRE_UP}
PostUp = ${POST_UP}
PreDown = ${PRE_DOWN}
PostDown = ${POST_DOWN}

[Peer]
Endpoint = ${END_POINT}
PublicKey = ${PUBLIC_KEY}
AllowedIPs = ${ALLOWED_IPS:-0.0.0.0/0}
PersistentKeepalive = ${PERSISTENT_KEEP_ALIVE:-25}
EOF
} && sync )

echo "[$(date -Iseconds)] Connecting..."
wg-quick up wg0 
echo "[$(date -Iseconds)] Connected! \(ᵔᵕᵔ)/"

if [[ -n ${RECONNECT} ]]; then
  echo "[$(date -Iseconds)] Reconnecting in ${RECONNECT} seconds"
fi
sleep "${RECONNECT:-infinity}"
