#!/usr/bin/with-contenv bash

ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
  echo "Wireguard module is active"
  ip link del dev test
else 
  echo "Uname info: $(uname -a)"
  echo "**** Unable to enable wireguard module, please install it on the host and try again (https://www.wireguard.com/install/). ****"
  sleep infinity
fi

if [[ -z ${PRIVATE_KEY} ]] ; then
  echo "**** Missing PRIVATE_KEY please review the documentation. ****"
  sleep infinity
fi