#!/usr/bin/with-contenv bash

ip link del dev test 2>/dev/null
if ip link add dev test type wireguard; then
  ip link del dev test
else
  echo "[$(date -Iseconds)] The wireguard module is not active, try \`docker run --rm --cap-add=NET_ADMIN --cap-add=SYS_MODULE -v /lib/modules:/lib/modules bubuntux/install-wireguard\` to install it or follow the proper instructions from https://www.wireguard.com/install/ to manually install it."
  sleep infinity
fi

if ! iptables -L > /dev/null 2>&1; then
  echo "[$(date -Iseconds)] iptables is not functional. Ensure your container config adds --cap-add=NET_RAW" 
  sleep infinity
fi

if [[ -z ${PRIVATE_KEY} ]] && [[ -z ${PRIVATE_KEY_FILE} ]] ; then
  echo "[$(date -Iseconds)] Missing PRIVATE_KEY, and, PRIVATE_KEY_FILE, try \`docker run --rm --cap-add=NET_ADMIN -e USER=XXX -e PASS=YYY bubuntux/nordvpn:get_private_key\` or follow this instructions https://forum.openwrt.org/t/instruction-config-nordvpn-wireguard-nordlynx-on-openwrt/89976 to obtain the private key."
  sleep infinity
fi