#!/usr/bin/with-contenv bash

[[ -n ${NETWORK} && -z ${NET_LOCAL} ]] && NET_LOCAL=${NETWORK}
if [ -n "$NET_LOCAL" ]; then
   iface=${INTERFACE:-eth0}
   gw="$(ip route | awk '/default/{print $3}')"
   for net in ${NET_LOCAL//[;,]/ }; do
     echo "[$(date -Iseconds)] Enabling connection to network ${net}"
      ip route | grep -q "$net" || ip route add "$net" via "$gw" dev "$iface"
      iptables -A INPUT   -i "$iface" -s "$net" -j ACCEPT
      iptables -A OUTPUT  -o "$iface" -d "$net" -j ACCEPT
      iptables -A FORWARD -i "$iface" -d "$net" -j ACCEPT
      iptables -A FORWARD -i "$iface" -s "$net" -j ACCEPT
  done
fi