#!/usr/bin/with-contenv bash

[[ -n ${NETWORK6} && -z ${NET6_LOCAL} ]] && NET6_LOCAL=${NETWORK6}
if [ -n "$NET6_LOCAL" ]; then
   iface=${INTERFACE:-eth0}
   gw="$(ip -6 route | awk '/default/{print $3}')"
   for net in ${NET6_LOCAL//[;,]/ }; do
      echo "[$(date -Iseconds)] Enabling connection to network ${net}"
      ip -6 route | grep -q "$net" || ip route add "$net" via "$gw" dev "$iface"
      ip6tables -A INPUT   -i "$iface" -s "$net" -j ACCEPT
      ip6tables -A OUTPUT  -o "$iface" -d "$net" -j ACCEPT
      ip6tables -A FORWARD -i "$iface" -d "$net" -j ACCEPT
      ip6tables -A FORWARD -i "$iface" -s "$net" -j ACCEPT
  done
fi