#!/bin/bash

network_found=false
interfaces=$(ip link | awk -F': ' '$0 !~ "lo|wg|tun|tap|^[^0-9]"{print $2;getline}' | cut -d@ -f1)
for iface in "${interfaces[@]}"; do
  inet="$(ip -o addr show dev "${iface}" | awk '$3 == "inet" {print $4}')"
  if [[ -z "$inet" ]]; then
    continue
  fi
  if [ "$network_found" = false ]; then
    iptables -F
    iptables -X
  fi
  echo "[$(date -Iseconds)] Enabling connection to ${iface} ${inet}"
  iptables -A INPUT -i "$iface" -s "${inet}" -j ACCEPT
  iptables -A OUTPUT -o "$iface" -d "${inet}" -j ACCEPT
  iptables -A FORWARD -i "$iface" -d "${inet}" -j ACCEPT
  iptables -A FORWARD -i "$iface" -s "${inet}" -j ACCEPT
  network_found=true
done

if [ "$network_found" = false ]; then
  echo "[$(date -Iseconds)] No interface network detected"
  exit
fi

echo "[$(date -Iseconds)] Enabling connection to secure interfaces"

iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A FORWARD -i lo -j ACCEPT

iptables -A OUTPUT -o wg+ -j ACCEPT
iptables -t nat -A POSTROUTING -o wg+ -j MASQUERADE

iptables -A OUTPUT -o eth0 -p udp -m udp --dport 53 -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
iptables -A OUTPUT -o eth0 -d api.nordvpn.com -p tcp --dport 443 -j ACCEPT
